/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtefactsRouteImport } from './routes/artefacts'
import { Route as ConnexionsRouteImport } from './routes/connexions'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as ParametresRouteImport } from './routes/parametres'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtefactsRoute = ArtefactsRouteImport.update({
  id: '/artefacts',
  path: '/artefacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionsRoute = ConnexionsRouteImport.update({
  id: '/connexions',
  path: '/connexions',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artefacts': typeof ArtefactsRoute
  '/connexions': typeof ConnexionsRoute
  '/dossiers': typeof DossiersRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notebook': typeof NotebookRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artefacts': typeof ArtefactsRoute
  '/connexions': typeof ConnexionsRoute
  '/dossiers': typeof DossiersRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notebook': typeof NotebookRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artefacts': typeof ArtefactsRoute
  '/connexions': typeof ConnexionsRoute
  '/dossiers': typeof DossiersRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notebook': typeof NotebookRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artefacts'
    | '/connexions'
    | '/dossiers'
    | '/inbox'
    | '/login'
    | '/notebook'
    | '/parametres'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artefacts'
    | '/connexions'
    | '/dossiers'
    | '/inbox'
    | '/login'
    | '/notebook'
    | '/parametres'
  id:
    | '__root__'
    | '/'
    | '/artefacts'
    | '/connexions'
    | '/dossiers'
    | '/inbox'
    | '/login'
    | '/notebook'
    | '/parametres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtefactsRoute: typeof ArtefactsRoute
  ConnexionsRoute: typeof ConnexionsRoute
  DossiersRoute: typeof DossiersRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  NotebookRoute: typeof NotebookRoute
  ParametresRoute: typeof ParametresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artefacts': {
      id: '/artefacts'
      path: '/artefacts'
      fullPath: '/artefacts'
      preLoaderRoute: typeof ArtefactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexions': {
      id: '/connexions'
      path: '/connexions'
      fullPath: '/connexions'
      preLoaderRoute: typeof ConnexionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtefactsRoute: ArtefactsRoute,
  ConnexionsRoute: ConnexionsRoute,
  DossiersRoute: DossiersRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  NotebookRoute: NotebookRoute,
  ParametresRoute: ParametresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtefactsRouteImport } from './routes/artefacts'
import { Route as ConnexionsRouteImport } from './routes/connexions'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as ParametresRouteImport } from './routes/parametres'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtefactsRoute = ArtefactsRouteImport.update({
  id: '/artefacts',
  path: '/artefacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionsRoute = ConnexionsRouteImport.update({
  id: '/connexions',
  path: '/connexions',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artefacts': typeof ArtefactsRoute
  '/connexions': typeof ConnexionsRoute
  '/dossiers': typeof DossiersRoute
  '/inbox': typeof InboxRoute
  '/notebook': typeof NotebookRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artefacts': typeof ArtefactsRoute
  '/connexions': typeof ConnexionsRoute
  '/dossiers': typeof DossiersRoute
  '/inbox': typeof InboxRoute
  '/notebook': typeof NotebookRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artefacts': typeof ArtefactsRoute
  '/connexions': typeof ConnexionsRoute
  '/dossiers': typeof DossiersRoute
  '/inbox': typeof InboxRoute
  '/notebook': typeof NotebookRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artefacts'
    | '/connexions'
    | '/dossiers'
    | '/inbox'
    | '/notebook'
    | '/parametres'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artefacts'
    | '/connexions'
    | '/dossiers'
    | '/inbox'
    | '/notebook'
    | '/parametres'
  id:
    | '__root__'
    | '/'
    | '/artefacts'
    | '/connexions'
    | '/dossiers'
    | '/inbox'
    | '/notebook'
    | '/parametres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtefactsRoute: typeof ArtefactsRoute
  ConnexionsRoute: typeof ConnexionsRoute
  DossiersRoute: typeof DossiersRoute
  InboxRoute: typeof InboxRoute
  NotebookRoute: typeof NotebookRoute
  ParametresRoute: typeof ParametresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artefacts': {
      id: '/artefacts'
      path: '/artefacts'
      fullPath: '/artefacts'
      preLoaderRoute: typeof ArtefactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexions': {
      id: '/connexions'
      path: '/connexions'
      fullPath: '/connexions'
      preLoaderRoute: typeof ConnexionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtefactsRoute: ArtefactsRoute,
  ConnexionsRoute: ConnexionsRoute,
  DossiersRoute: DossiersRoute,
  InboxRoute: InboxRoute,
  NotebookRoute: NotebookRoute,
  ParametresRoute: ParametresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
